---
title: "milestone1"
format: html
editor: visual
---

---
title: "Milestone 1 - Stat212"
author: "Aki + Alec"
format: html
editor: visual
---

## MileStone 1

Names: Aki and Alec

Project Topic: Conduct sentiment analysis and emotional analysis on Podcasts

Questions:

- How do the textual emotion of a word and the intonation the word is used with relate? (where textual emotion is the emotion a word gives when read)

- How to create a popular podcast?

Data: Scraped RSS Feeds for Podcasts: `The Daily` and `The Joe Rogan Experience` 

Data Context: 

- Who: People who are speaking into their microphones for the podcast.   

- What: Podcast metadata about popularity as well as full length podcast audio

- When: Podcast data ranging from 2013-2023

- Where: Within the world wide web. Most RSS feeds exist on podnews.com

- Why: In order to determine what makes a podcast successful or not as well as understand speech patterns. 

- How: Scraping RSS Feeds from `podnews.com` with the podcast audio link.


Data Codebook using the RSS API:

- Podcast Title: {title}
- Subtitle: {subtitle}"
- Link: {link}"
- Image URL: {image_url}
- Summary: {summary}
- Language: {language}
- Rights: {rights}")
- Published: {published}
- Updated: {updated}"
- Author: {author} 
- Tags: {', '.join(tags)}"
- Links: {links}"


Plan: Using a audio-to-speech github library as well as information about the view count of the those podcasts on major platforms like spotify or youtube, we conduct sentiment analysis on the transcripts of podcasts as well as analyze the metadata on the podcast to determine what makes a podcast popular and how the textual emotion of a word and the intonation the word is used with, relate.

For our 2.5 week plan, we plan to 

1. load audio into a github speech-to-text analyzer

2. write our own sentiment analysis script to analyze given text

3. take given sentiment (interpreted by our script) and compare it to a database of what certain emotions words are associated with. 

4. create a simple linear model to find the relationship between all the metadata (from the rss feed) with the textual emotion and intonation as variables to predict the popularity of said podcast.
