---
title: "Milestone 1 - Stat212"
author: "Aki + Alec"
format: html
editor: visual
---

## MileStone 1

Linguistics

Social Media - Hard nowadays because vendors lock their data

Audio

Podcasts
Music

Podcasts: 
Sentiment Analysis
Words (interpreted)
Voice (emotion)
Predictive Popularity Modeling
Audience Insights Through Review Analysis


Names: Aki and Alec
Project Topic: Conduct sentiment analysis and emotional analysis on Podcasts
Questions:
How do interpreted words and interpreted emotion relate?
How to create a popular podcast given a popular podcast structure?

Data: Find one data source, and read that data into R.



Data Context: Thoroughly describe the data context (who, what, when, where, why, and how? questions related to the dataset).


Data Codebook: Write up a data codebook. That is, describe the type and meaning of the variables in your dataset. Group your variables into categories (e.g., demographic variables, neighborhood variables).
If you have a lot of variables, it may not be necessary/feasible to describe every variable individually. Rather, you can describe groups of similar variables.


Plan: Based on the data context write-up and your codebook, describe which of your 2-3 broad questions can be addressed with your dataset and how.
Write a plan for addressing these questions. Make sure that the steps in this plan are reasonable to complete in about 2.5 weeks for Milestone 2. You will receive feedback on this plan and will be expected to integrate this feedback for Milestone 2.


https://github.com/MiteshPuthran/Speech-Emotion-Analyzer



We will take 100 podcasts. And around 50 episodes of each podcast? (https://explodingtopics.com/blog/number-of-podcasts)

Try not to sample from beginning 
