---
title: "Blog Post"
format: html
editor: visual
---

## Blog Post

Dear Reader,

So this post will be on the project my team is working on for our data science project. In this project we using sentiment analysis to try to find the similarities between podcast and news articles when it comes down to their content.

In the modern era it seems that people are moving farther and farther away from print media. With the advent of the 24 hour news cycle started at the turn of the century and the ever present diminishing attention span, People are now consuming their news in different media than their parents generation. Even as newspapers evolve more to be online in forms of online posts and websites, more people are more engaged in media that can be listened to. So as news changes the way it is dispersed how does that change the way news is received?

In our project we are specifically looking at the "sentiment" of podcast episodes and news articles. First we wanted to get a consistent type of content from both the articles and the podcast. So we decided that meant we used the same source for both, Vox. Vox has both a news podcast section called "Voxxed: Explained" and a standard print news section. This made it easy to standardize the data, consistently if they write about a topic they will create a podcast episode for that topic. Then using the podcast transcript and the print news, we used Baer's Niave base to gain the overall sentiment of the pieces.

Unfortunately, due to scheduling difficulties and time constraints we have only analysed the podcast side of the data, although this is only one side of the story we can actually tell some interesting things about our current news climate within last year. Hopefully with more time we can go further back in time and see trends appear and how they differ or match the print media.

Looking at the first graph, it represents the frequency of words being used. This means how often a unique word appears in the podcast. And as we can see it the uniqueness of words are not that large. It seems that the frequency at which podcast use unique word trends towards less as we say more words.

Of course we have to add the word cloud, as it is just kind of a fun visualization to use(even if it can be a little bit useless when it comes to data), but we can see a lot of the common words are similar to those studies which analyze common words in books.

As we are struggling with some tech difficulties(I need to get a new computer ASAP), these vizualizations will be available to see in this code folder at the moment but will change to be in a figure folder.
